### ISSUE TITLE
와우~ 충분히 우아하고 멋지게 해결하셨네요..^^;

### ISSUE THREAD

**Issue by jeongjaehong** [yongbin/parameterize-calendar-mysql#2]
와우~ 충분히 우아하고 멋지게 해결하셨네요..^^;

멋지십니다...^^;

이 문제를 출제하고 하루 이틀 만엔가 실무에 직접 사용할 일이 생기더군요...물론 오라클이었지만...

대충 내용은 이랬습니다...
1. 인사정보가 있습니다.
2. 출퇴근 기록이 있습니다.
3. 외근등록정보가 있습니다.

요구사항은 이렇습니다.
특정 기간동안의 각 개인의 출퇴근 기록을 표시하되 외근등록된 사람은 외근등록정보를 표시하는 상황이었습니다.

1,2,3에서 주어진 어떤 테이블도 기준테이블로 사용할 수가 없더군요..^^;

그래서 조회기준이 되는 기간에 해당하는 날짜 목록을 달력을 생성할때 처럼 생성하고 인사정보를 cross조인하고 출퇴근 정보와 외근등록정보를 각각 left join 처리를 해서 처리하도록 했습니다...ㅎㅎ

의외로 이런식으로 가상의 테이블을 생성해서 작업해야 하는 실무가 많은것 같습니다...^^;

멋진 문제풀이 잘 보고 갑니다...

**Comment by yongbin** [comment]
앗 안녕하세요? 출제해 주신 분이군요 ;-) 반갑습니다.

네 말씀하신것 처럼 주로 DB 설계에 문제가 있는경우거나 현실적으로 DB 구조를 변경하기 어려울때 이런문제에 봉착하는데, 키가 되는 컬럼을 이런 꼼수들을 이용해서 생성하면 그나마 수월하게 문제를 해결할수 있어서 저도 자주 애용합니다. 

다만 pg 나 다른 RDBMS에서는 이런 복잡한 쿼리사용을 감안한 다양한 지원이 있는데 MySQL은 그런 지원이 상대적으로 좀 약해서 여러가지 우회방법을 고심해야하고 결과적으로 쿼리 문도 길어지는것 같습니다.

흥미로운 문제 출제해주시고 의견까지 남겨주셔서 감사합니다.
